Efc 71 add objects to world
Roboy/bulletroboy pull request #11
Opened 2020-06-08 22:34 UTC by NadaChatti

Now you can:
- define position and size of cube to add
- add cube
- add fixed cube (needed for debugging collision issues)
- delete cubes added

2020-06-10 14:48 UTC, missxa requested changes
looks good, only a minor change with logging and good to merge

2020-06-10 14:48 UTC, missxa commented on bulletroboy/ros2_roboy.py
> +    print(file_path)
use ros2 logging instead of printing, like so 
`  node.get_logger().info("sdf")`

2020-06-10 14:48 UTC, missxa commented on bulletroboy/ros2_roboy.py
>          parser.error("The file %s does not exist!" % file_path)
also get_logger().error

2020-06-11 09:02 UTC, NadaChatti commented on bulletroboy/ros2_roboy.py
> +    print(file_path)
That was actually just used for debugging, we do not need it

2020-06-11 09:05 UTC, NadaChatti commented on bulletroboy/ros2_roboy.py
>          parser.error("The file %s does not exist!" % file_path)
This is a method that is not inside any  Class so using node would need a new Class that would inherit from node just for file loading, do we need that?

2020-06-11 09:07 UTC, NadaChatti commented on bulletroboy/ros2_roboy.py
>          parser.error("The file %s does not exist!" % file_path)
Also if I change this, I need to change it in all other scripts for consistency, right?

2020-06-11 11:58 UTC, missxa commented on bulletroboy/ros2_roboy.py
>          parser.error("The file %s does not exist!" % file_path)
There is rclpy.logging._root_logger.debug('message_debug') that you can use without a node

2020-06-14 14:11 UTC, missxa approved these changes

2020-06-14 15:28 UTC, merged