Added service to get initial end efectors configuration
Roboy/bulletroboy pull request #17
Opened 2020-06-18 23:24 UTC by mlanas

A service was added in ExoForce class (cage_simulation node) to allow other nodes to retrieve the initial configuration from the XML file.
The first via_point of each muscle unit (motor position)  is not included in the response, given that this changes which cage rotation and its part of the cage state, NOT initial configuration.

The cage state publisher was modified to not publish the via_points attached to the operator, it only publishes the first via_point (motor position).

2020-06-19 16:54 UTC, missxa commented
> The first via_point of each muscle unit (motor position) is not included in the response, given that this changes which cage rotation and its part of the cage state, NOT initial configuration.
> 
> The cage state publisher was modified to not publish the via_points attached to the operator, it only publishes the first via_point (motor position).

i don't understand the motivation for these decisions. it will be very confusing I think. if you have to explain it now, everyone reading the code will have questions. why not publish cage state with all viapoints (it is in fact the state of the cage, cause tendons are a part of the cage)?
i don't see the reason why not include the motor position in the init config srv. it is a part of the initial state, and yea it will change and you will get the updates for that.

2020-06-20 09:19 UTC, mlanas commented
> > The first via_point of each muscle unit (motor position) is not included in the response, given that this changes which cage rotation and its part of the cage state, NOT initial configuration.
> > The cage state publisher was modified to not publish the via_points attached to the operator, it only publishes the first via_point (motor position).
> 
> i don't understand the motivation for these decisions. it will be very confusing I think. if you have to explain it now, everyone reading the code will have questions. why not publish cage state with all viapoints (it is in fact the state of the cage, cause tendons are a part of the cage)?
> i don't see the reason why not include the motor position in the init config srv. it is a part of the initial state, and yea it will change and you will get the updates for that.

Will apply the changes

2020-06-21 15:42 UTC, missxa requested changes

2020-06-21 15:42 UTC, missxa commented on bulletroboy/exoforce.py
> +				muscle_msg = MuscleUnitMsg()
- [ ] add `to_msg()` method in `MuscleUnit` class instead of doing it here

2020-06-21 15:42 UTC, missxa commented on bulletroboy/exoforce.py
> +					via_point_msg = ViaPoint()
same here, we could have a convenience `ViaPoint` class. wouldn't it be better?

2020-06-21 15:42 UTC, missxa commented on bulletroboy/exoforce.py
> +				muscle_msg = MuscleUnitMsg()
so you'd have something like
```python
for muscle in self.get_ef_muscle_units(ef):
   muscle_msg = muscle.to_msg() # viapoints to msg would be nested in that function
   end_effector_msg.muscle_units.append(muscle_msg)
```

2020-06-21 21:17 UTC, missxa approved these changes

2020-06-21 21:20 UTC, merged