Optimization
Roboy/bulletroboy pull request #20
Opened 2020-06-25 13:32 UTC by MichaelHeiss

so I think the optimization file is working and I tried to document everything. would be nice to get some feedback on that.

2020-06-25 15:24 UTC, MichaelHeiss commented
sorry i found some errors and had to fix those before the revue but i don't know whether i did this right. please excuse me.

2020-07-11 21:33 UTC, mlanas requested changes

2020-07-11 21:33 UTC, mlanas commented on bulletroboy/optimization.py
> +#__main__
Would better to have an if main statement like:
`if __name__ == "__main__":`

2020-07-11 21:33 UTC, mlanas commented on bulletroboy/optimization.py
> +from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import
If the import is not used, it should be deleted

2020-07-14 14:49 UTC, missxa requested changes

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +    if joint == "human/left_wrist":
remove hardcoded names of the joints

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +    for i, (mx, my, mz) in enumerate(zip(xx, yy, zz)):
add comments in this function explaining what you're doing and the magic numbers

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +text_file = open(f"../../Desktop/{solver}_02.txt", "wt")
remove hardcoded path

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +        joint (str):                        Information about the left or right wrist
passing joint names as strings is prone to errors or typos. it is not a good practice. if you need to distinguish between left and right you can pass a bool `isRight`.  in case you need link names, they should not be hardcoded in the optimizer, but read from a config/ yaml file or requested from a robot or human. worst case defined in the main function

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +        angles (numpy.array):               Angles of the tendons with respect to the x-axis
you mean between the angle and x-axis?

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +def force_decomposition(force_vector, force_point, tendons, attachment_points):
why is `force_decomposition` defined in the optimization? it doesn't belong here and must be identical for every module where it's used

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +def get_attachment_points(radius, height, angles, joint):
why do you need to calculate attachment points of the tendons if the config file provides this information?

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +    """ This function calculates the ergonomic workspace of the arm of a standing person
calculates based on what?

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +        param (numpy.array):                Vector containing position parameters for the tendon attachment points
explain the order of the values in param

2020-07-14 14:49 UTC, missxa commented on bulletroboy/optimization.py
> +print(solution)
this is a general comment on all of your prints: please add a debug message to all the variables that you print. you know that it's solution printed here, but nobody else

2020-08-04 13:23 UTC, missxa commented
@MichaelHeiss please resolve conflicts with the base branch

2020-12-08 14:46 UTC, closed without merging