Closing loop newdraft
Roboy/bulletroboy pull request #22
Opened 2020-07-14 16:31 UTC by KarimAlweheshy

2020-07-17 08:50 UTC, NadaChatti commented
I thought we agreed to make PRs for each branch and NOT use this one? This has a LOT of stuff that should not be in the develop branch..

2020-07-17 09:21 UTC, mlanas commented
> I thought we agreed to make PRs for each branch and NOT use this one? This has a LOT of stuff that should not be in the develop branch..

Last meeting we agreed to merge this one, so the idea is to clean this branch for merging with ss20_devel

2020-07-22 20:20 UTC, missxa requested changes

2020-07-22 20:20 UTC, missxa commented on bulletroboy/exoforce_simulation.py
> +				self.create_subscription(Collision, '/roboy/exoforce/collisions', self.collision_listener, 10)
decrease queue size to 1

2020-07-22 20:20 UTC, missxa commented on bulletroboy/exoforce_simulation.py
>  			self.create_subscription(Float32, '/roboy/simulation/cage_rotation', self.cage_rotation_listener, 10)
decrease queue size to 1

2020-07-22 20:20 UTC, missxa commented on bulletroboy/exoforce_simulation.py
> +		self.get_logger().info('Received collision message in roboy link %i' % collision.linkid)
throttle this log, limit to once per second or per 5 seconds

2020-07-22 20:20 UTC, missxa commented on bulletroboy/exoforce_simulation.py
> +				self.create_subscription(Collision, '/roboy/exoforce/collisions', self.collision_listener, 10)
`/roboy/simulation/(exoforce)/operator/collisions`is a more suitable name

2020-07-22 20:20 UTC, missxa commented on bulletroboy/exoforce_simulation.py
> +			print('force_end: ', force_end)
no prints please

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +            '/roboy/simulation/collision',
`roboy/simulation/roboy/collision`?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +            10)
decrease queue size to 1

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        self.exoforceCollisionPublisher = self.create_publisher(Collision, '/roboy/exoforce/collisions', 10)
see my comment on the topic name in exoforce file

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        self.exoforceCollisionPublisher = self.create_publisher(Collision, '/roboy/exoforce/collisions', 10)
decrease queue size to 1

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        self.get_logger().info('Received collision')
throttle info prints once every 2 or 3 seconds is enough

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        """Calculates the collision on the human and assign it to the 'result' var.
incorrect docstring

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        self.transform_from_roboy_to_operator(msg)
it's confusing that the function is called transform but it's publishing too.. i suggest to publish from this method

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        self.get_logger().info("publishing")
no need, if you want it  use `.debug()` and set an appropriate logging level

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        self.get_logger().info('mapping start')
same, use debug if you want to keep this

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        self.get_logger().info('mapping start')
wont comment on the future unnecessary logs

2020-07-22 20:20 UTC, missxa commented on bulletroboy/forces_mapper.py
> +        rel_path = "../resource/roboy_to_human_linkname_map.yaml"
can you guarantee that this relative path works independent from the way i execute your code?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/operator.py
> +		p.createConstraint(self.body_id, -1, -1, -1, p.JOINT_FIXED, [0,0,0],[0,0,0],[0,0,0],[0,0,0,1])
what is this for?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/operator.py
> +		"""Gets link's center point in world frame.
what is a center point? center of mass you mean?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/operator.py
> +		Args:
incorrect docstring

2020-07-22 20:20 UTC, missxa commented on bulletroboy/operator.py
> +			case (int): Movement to apply.
where to find these ints?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/operator.py
> +		   self.drawDebugLines(ef, link_pos)
why is there drawing in a publisher?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/operator.py
> +		head = self.get_link_index(request.link_name)
why is this called head?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +        p.addUserDebugLine([0,0,0],[0,0,0.3],[0,0,1],lineWidth= 3, parentObjectUniqueId=self.body_id, parentLinkIndex=47)
can we do this in  a more optimal way?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +        timer_period = 0.1 # seconds
joints must be published more often, at least 50hz, better 100hz

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
>          self.collision_publisher = self.create_publisher(Collision, '/roboy/simulation/collision', 1)
```suggestion
        self.collision_publisher = self.create_publisher(Collision, '/roboy/simulation/roboy/collision', 1)
```

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +        return response
all these fucntions are exact copies of the ones defined for the operator, please optimise and remove copy-paste

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +    def move(self, link_info):
docstrings?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +        ef_name = OPERATOR_TO_ROBOY_NAMES[link_info.header.frame_id]
this is not using forces/link mapper? if not, it should

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +        ef_name = OPERATOR_TO_ROBOY_NAMES[link_info.header.frame_id]
we agreed to delegate all of the mapping to that other node, so neither roboy nor operator simulations should not deal with finding corresponding link names/ids.

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +    def accurateCalculateInverseKinematics(self, endEffectorId, targetPos, targetOrn, threshold, maxIter):
add defaults to threshold and maxiter

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +    def get_pos_in_world(self, pos, orn):
docstrings missing

also, pos of what?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +    def adapt_pos_to_roboy(self, pos, orn):
adapt from what to what?

2020-07-22 20:20 UTC, missxa commented on bulletroboy/roboy.py
> +    def axis_angle_to_quaternion(self, ax, ay, az, angle):
another util function candidate , doesnt need to be a method in roboy

2020-07-22 20:22 UTC, missxa commented
a lot of docstrings are missing. also you may remove draft from the PR name

2020-07-23 12:53 UTC, KarimAlweheshy commented on bulletroboy/forces_mapper.py
> +        rel_path = "../resource/roboy_to_human_linkname_map.yaml"
well.. unless someone removes/moves/renames the file it ill work

How do you suggest guaranteeing it?

2020-08-11 18:50 UTC, missxa approved these changes

2020-08-11 18:55 UTC, merged